repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4        
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.10
